"use client";
import { DataProvider } from "./components/context/Authcontext";
import "./globals.css";
import { ThemeProvider, createTheme } from "@mui/material/styles";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = createTheme({
    breakpoints: {
      values: {
        xs: 0,
        sm: 314,
        smm: 530,
        md: 768,
        lg: 1024,
        xl: 1220,
        xll: 1440,
        xxl: 1600,
      },
    },
  });
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <DataProvider>
          <body>{children}</body>
        </DataProvider>
      </ThemeProvider>
    </html>
  );
}
